services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: UserInterface.Web/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "28017:28017" 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASS:-adminpassword}