services:
  userinterface.web:
    image: ${DOCKER_REGISTRY-}userinterfaceweb
    build:
      context: .
      dockerfile: UserInterface.Web/Dockerfile
    links:
      - "mongodb:database"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017" 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASS:-adminpassword}